drop table ol_usuario;
drop table ol_animal;
drop table ol_especie;
drop table ol_genero;
drop table ol_familia;
drop table ol_cuidador;
drop table ol_persona;
drop table ol_zoologico;
drop table ol_pais;
commit;


CREATE TABLE OL_ANIMAL
  (
    anim_id   NUMBER NOT NULL ,
    anim_nomb VARCHAR2 (30) NOT NULL ,
    anim_sexo CHAR (1) NOT NULL ,
    anim_peso NUMBER (6,2) ,
    anim_fnac DATE ,
    espe_id   NUMBER NOT NULL ,
    zool_id   NUMBER NOT NULL ,
    cuid_id   NUMBER NOT NULL ,
    pais_id   NUMBER NOT NULL
  )
  ;
ALTER TABLE OL_ANIMAL ADD CONSTRAINT OL_ANIMAL_PK PRIMARY KEY ( anim_id ) ;
CREATE TABLE OL_CUIDADOR
  (
    cuid_id   NUMBER NOT NULL ,
    cuid_freg DATE NOT NULL ,
    cuid_esta CHAR (1) NOT NULL ,
    pers_id   NUMBER NOT NULL
  )
  ;
ALTER TABLE OL_CUIDADOR ADD CONSTRAINT OL_CUIDADOR_PK PRIMARY KEY ( cuid_id ) ;
CREATE TABLE OL_ESPECIE
  (
    espe_id   NUMBER NOT NULL ,
    espe_nomc VARCHAR2 (30) NOT NULL ,
    espe_nomv VARCHAR2 (30) NOT NULL ,
    gene_id   NUMBER NOT NULL
  )
  ;
ALTER TABLE OL_ESPECIE ADD CONSTRAINT OL_ESPECIE_PK PRIMARY KEY ( espe_id ) ;
CREATE TABLE OL_FAMILIA
  (
    fami_id   NUMBER NOT NULL ,
    fami_nomb VARCHAR2 (30) NOT NULL
  )
  ;
ALTER TABLE OL_FAMILIA ADD CONSTRAINT OL_FAMILIA_PK PRIMARY KEY ( fami_id ) ;
CREATE TABLE OL_GENERO
  (
    gene_id   NUMBER NOT NULL ,
    gene_nomb VARCHAR2 (30) NOT NULL ,
    fami_id   NUMBER NOT NULL
  )
  ;
ALTER TABLE OL_GENERO ADD CONSTRAINT OL_GENERO_PK PRIMARY KEY ( gene_id ) ;
CREATE TABLE OL_PAIS
  (
    pais_id   NUMBER NOT NULL ,
    pais_nomb VARCHAR2 (30) NOT NULL
  )
  ;
ALTER TABLE OL_PAIS ADD CONSTRAINT OL_PAIS_PK PRIMARY KEY ( pais_id ) ;
CREATE TABLE OL_PERSONA
  (
    pers_id   NUMBER NOT NULL ,
    pers_nomb VARCHAR2 (30) NOT NULL ,
    pers_apel VARCHAR2 (30) NOT NULL ,
    pers_dire VARCHAR2 (50) ,
    pais_id   NUMBER NOT NULL,
    pers_esta char(1) not null
  )
  ;
ALTER TABLE OL_PERSONA ADD CONSTRAINT OL_PERSONA_PK PRIMARY KEY ( pers_id ) ;
CREATE TABLE OL_USUARIO
  (
    user_id   NUMBER NOT NULL ,
    user_user VARCHAR2 (30) NOT NULL ,
    user_pass VARCHAR2 (30) NOT NULL ,
    user_carg CHAR (1) NOT NULL ,
    user_esta CHAR (1) NOT NULL ,
    pers_id   NUMBER NOT NULL
  )
  ;
ALTER TABLE OL_USUARIO ADD CONSTRAINT OL_USUARIO_PK PRIMARY KEY ( user_id ) ;
CREATE TABLE OL_ZOOLOGICO
  (
    zool_id   NUMBER NOT NULL ,
    zool_nomb VARCHAR2 (30) NOT NULL ,
    zool_anio NUMBER ,
    zool_ciud VARCHAR2 (30) ,
    pais_id   NUMBER NOT NULL
  )
  ;
ALTER TABLE OL_ZOOLOGICO ADD CONSTRAINT OL_ZOOLOGICO_PK PRIMARY KEY ( zool_id ) ;
ALTER TABLE OL_ANIMAL ADD CONSTRAINT OL_ANIMAL_OL_CUIDADOR_FK FOREIGN KEY ( cuid_id ) REFERENCES OL_CUIDADOR ( cuid_id ) NOT DEFERRABLE ;
ALTER TABLE OL_ANIMAL ADD CONSTRAINT OL_ANIMAL_OL_ESPECIE_FK FOREIGN KEY ( espe_id ) REFERENCES OL_ESPECIE ( espe_id ) NOT DEFERRABLE ;
ALTER TABLE OL_ANIMAL ADD CONSTRAINT OL_ANIMAL_OL_PAIS_FK FOREIGN KEY ( pais_id ) REFERENCES OL_PAIS ( pais_id ) NOT DEFERRABLE ;
ALTER TABLE OL_ANIMAL ADD CONSTRAINT OL_ANIMAL_OL_ZOOLOGICO_FK FOREIGN KEY ( zool_id ) REFERENCES OL_ZOOLOGICO ( zool_id ) NOT DEFERRABLE ;
ALTER TABLE OL_CUIDADOR ADD CONSTRAINT OL_CUIDADOR_OL_PERSONA_FK FOREIGN KEY ( pers_id ) REFERENCES OL_PERSONA ( pers_id ) NOT DEFERRABLE ;
ALTER TABLE OL_ESPECIE ADD CONSTRAINT OL_ESPECIE_OL_GENERO_FK FOREIGN KEY ( gene_id ) REFERENCES OL_GENERO ( gene_id ) NOT DEFERRABLE ;
ALTER TABLE OL_GENERO ADD CONSTRAINT OL_GENERO_OL_FAMILIA_FK FOREIGN KEY ( fami_id ) REFERENCES OL_FAMILIA ( fami_id ) NOT DEFERRABLE ;
ALTER TABLE OL_PERSONA ADD CONSTRAINT OL_PERSONA_OL_PAIS_FK FOREIGN KEY ( pais_id ) REFERENCES OL_PAIS ( pais_id ) NOT DEFERRABLE ;
ALTER TABLE OL_USUARIO ADD CONSTRAINT OL_USUARIO_OL_PERSONA_FK FOREIGN KEY ( pers_id ) REFERENCES OL_PERSONA ( pers_id ) NOT DEFERRABLE ;
ALTER TABLE OL_ZOOLOGICO ADD CONSTRAINT OL_ZOOLOGICO_OL_PAIS_FK FOREIGN KEY ( pais_id ) REFERENCES OL_PAIS ( pais_id ) NOT DEFERRABLE ;

commit;